name: UCH-tirosinemia
channels:
  - conda-forge

dependencies:
  # Lectura de parametros y data
  - gspread
  - yaml
  # Computacion numerica
  - numpy
  - optuna
  - pandas
  - ray-core
  - grpcio=1.46.3
  # ML
  - scikit-learn
  - xgboost
  - shap
  # Graficos
  - plotly
  - seaborn
